"""Add pausing, work time and execution report to orders

Revision ID: 2681150802e8
Revises: 40ef0329d599
Create Date: 2026-08-09 21:13:55.605469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "2681150802e8"
down_revision: Union[str, Sequence[str], None] = "40ef0329d599"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_calendar",
        sa.Column(
            "execution_report",
            sa.String(),
            nullable=True,
            comment="Detailed report of the work performed, including observations and outcomes",
        ),
    )
    op.add_column(
        "order_calendar",
        sa.Column(
            "pause_reason",
            sa.String(),
            nullable=True,
            comment="Reason for pausing the task, if applicable",
        ),
    )
    op.add_column(
        "order_calendar",
        sa.Column(
            "is_machine_operational",
            sa.Boolean(),
            nullable=True,
            comment="Indicates if the machine is operational",
        ),
    )
    op.add_column(
        "order_calendar",
        sa.Column(
            "work_time_minutes",
            sa.Integer(),
            nullable=True,
            comment="Total time spent on the task in minutes",
        ),
    )
    op.add_column(
        "order_calendar",
        sa.Column(
            "last_resumed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the task was last resumed",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_calendar", "last_resumed_at")
    op.drop_column("order_calendar", "work_time_minutes")
    op.drop_column("order_calendar", "is_machine_operational")
    op.drop_column("order_calendar", "pause_reason")
    op.drop_column("order_calendar", "execution_report")
    # ### end Alembic commands ###
