"""add department_id to message

Revision ID: 3f858e85fd41
Revises: 976576caa33b
Create Date: 2026-08-17 18:11:52.290510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3f858e85fd41"
down_revision: Union[str, Sequence[str], None] = "976576caa33b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "department_id",
            sa.Integer(),
            nullable=True,
            comment="Optional department-based broadcast target",
        ),
    )
    op.create_foreign_key(None, "messages", "departments", ["department_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "messages", type_="foreignkey")
    op.drop_column("messages", "department_id")
    # ### end Alembic commands ###
