"""Add time tracking and priority to orders

Revision ID: 40ef0329d599
Revises: 7be7a9df85e6
Create Date: 2026-08-08 14:45:05.480861

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "40ef0329d599"
down_revision: Union[str, Sequence[str], None] = "7be7a9df85e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_calendar",
        sa.Column(
            "priority",
            sa.String(length=50),
            nullable=True,
            comment="Priority level of the order (e.g., 'low', 'normal', 'high')",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_calendar", "priority")
    # ### end Alembic commands ###
