"""add producer column

Revision ID: 4d1e8738aa8e
Revises: 9c8941f9246a
Create Date: 2026-07-25 18:46:45.581306

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "4d1e8738aa8e"
down_revision: Union[str, Sequence[str], None] = "9c8941f9246a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "order_checklist_items",
        "task_description",
        existing_type=sa.VARCHAR(),
        nullable=True,
        existing_comment="Detailed instruction for this specific checklist step",
    )
    op.add_column(
        "parts",
        sa.Column(
            "producer",
            sa.String(),
            nullable=True,
            comment="Manufacturer or supplier of the part",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("parts", "producer")
    op.alter_column(
        "order_checklist_items",
        "task_description",
        existing_type=sa.VARCHAR(),
        nullable=False,
        existing_comment="Detailed instruction for this specific checklist step",
    )
    # ### end Alembic commands ###
