"""Add auth fields to users and fix attachment failure_id

Revision ID: 5875d9cb6f71
Revises: fc5443389ed0
Create Date: 2026-07-09 17:24:21.157842

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "5875d9cb6f71"
down_revision: Union[str, Sequence[str], None] = "fc5443389ed0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "attachments",
        "failure_id",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_comment="Foreign key to the failures table",
    )
    op.add_column(
        "users",
        sa.Column(
            "password",
            sa.String(),
            nullable=False,
            comment="Hashed password of the user",
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Indicates if the user is active",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_active")
    op.drop_column("users", "password")
    op.alter_column(
        "attachments",
        "failure_id",
        existing_type=sa.INTEGER(),
        nullable=False,
        existing_comment="Foreign key to the failures table",
    )
    # ### end Alembic commands ###
