"""add part_history table

Revision ID: 725eb1cdc487
Revises: 4d1e8738aa8e
Create Date: 2026-08-07 08:31:03.591667

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "725eb1cdc487"
down_revision: Union[str, Sequence[str], None] = "4d1e8738aa8e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
