"""Add time tracking to orders

Revision ID: 7be7a9df85e6
Revises: f5b6f694b182
Create Date: 2026-08-08 14:19:32.530547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7be7a9df85e6"
down_revision: Union[str, Sequence[str], None] = "f5b6f694b182"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_calendar",
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the task execution began",
        ),
    )
    op.add_column(
        "order_calendar",
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Timestamp when the task execution was completed",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_calendar", "completed_at")
    op.drop_column("order_calendar", "started_at")
    # ### end Alembic commands ###
