"""Add connection between departmant and user

Revision ID: 976576caa33b
Revises: 2681150802e8
Create Date: 2026-08-15 08:55:13.331388

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "976576caa33b"
down_revision: Union[str, Sequence[str], None] = "2681150802e8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "department_id",
            sa.Integer(),
            nullable=True,
            comment="Optional link to the department the user belongs to",
        ),
    )
    op.create_foreign_key(None, "users", "departments", ["department_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_column("users", "department_id")
    # ### end Alembic commands ###
