"""Add timezone to timestamps

Revision ID: 980fb942c02f
Revises: 725eb1cdc487
Create Date: 2026-08-07 21:47:02.067295

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "980fb942c02f"
down_revision: Union[str, Sequence[str], None] = "725eb1cdc487"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_calendar_id"), table_name="order_calendar")
    op.drop_table("order_calendar")
    op.drop_table("part_compatibilities")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_table("message_recipients")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_machines_id"), table_name="machines")
    op.drop_table("machines")
    op.drop_index(op.f("ix_parts_id"), table_name="parts")
    op.drop_table("parts")
    op.drop_index(op.f("ix_part_history_id"), table_name="part_history")
    op.drop_table("part_history")
    op.drop_index(op.f("ix_attachments_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_index(op.f("ix_failures_id"), table_name="failures")
    op.drop_table("failures")
    op.drop_table("failure_parts")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_table("departments")
    op.drop_index(op.f("ix_part_categories_id"), table_name="part_categories")
    op.drop_table("part_categories")
    op.drop_index(
        op.f("ix_order_checklist_items_id"), table_name="order_checklist_items"
    )
    op.drop_table("order_checklist_items")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_order_types_id"), table_name="order_types")
    op.drop_table("order_types")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_types",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Unique identifier/name for the order type category",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_types_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("order_types_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Dictionary of standardized maintenance order categories",
    )
    op.create_index(op.f("ix_order_types_id"), "order_types", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "password",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Securely hashed password for authentication",
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Determines if the user can currently access the system",
        ),
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Given name of the employee",
        ),
        sa.Column(
            "lastname",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Surname of the employee",
        ),
        sa.Column(
            "sap_number",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Unique identifier from SAP system",
        ),
        sa.Column(
            "role_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Determines the access level and permissions for the user",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the record was initially created",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the record was last modified",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("users_role_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("users_pkey")),
        sa.UniqueConstraint(
            "sap_number",
            name=op.f("users_sap_number_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Registry of system users and their authentication data",
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "order_checklist_items",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "order_calendar_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the parent maintenance order",
        ),
        sa.Column(
            "task_description",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Detailed instruction for this specific checklist step",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Completion status (e.g., 'pending', 'completed', 'not_applicable')",
        ),
        sa.Column(
            "comments",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Technician's notes or findings specific to this checklist item",
        ),
        sa.ForeignKeyConstraint(
            ["order_calendar_id"],
            ["order_calendar.id"],
            name=op.f("order_checklist_items_order_calendar_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_checklist_items_pkey")),
        comment="Granular task items belonging to a maintenance order checklist",
    )
    op.create_index(
        op.f("ix_order_checklist_items_id"),
        "order_checklist_items",
        ["id"],
        unique=False,
    )
    op.create_table(
        "part_categories",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Unique identifier/name for the part category",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("part_categories_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("part_categories_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Dictionary of spare part categories for inventory organization",
    )
    op.create_index(
        op.f("ix_part_categories_id"), "part_categories", ["id"], unique=False
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Official name of the department (e.g., Electrical, Mechanical)",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("departments_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("departments_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Organizational units responsible for handling machine failures",
    )
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_table(
        "failure_parts",
        sa.Column(
            "failure_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the repaired failure",
        ),
        sa.Column(
            "part_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the specific spare part consumed",
        ),
        sa.Column(
            "quantity_used",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Number of units removed from inventory for this repair",
        ),
        sa.ForeignKeyConstraint(
            ["failure_id"], ["failures.id"], name=op.f("failure_parts_failure_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["part_id"], ["parts.id"], name=op.f("failure_parts_part_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "failure_id", "part_id", name=op.f("failure_parts_pkey")
        ),
        comment="Association table tracking inventory consumed during failure repairs",
    )
    op.create_table(
        "failures",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "submitter_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the user who initially reported the issue",
        ),
        sa.Column(
            "machine_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the broken or malfunctioning machine",
        ),
        sa.Column(
            "department_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the department responsible for the repair",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Current lifecycle state (e.g., 'open', 'in_progress', 'closed')",
        ),
        sa.Column(
            "recipient_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Reference to the mechanic or technician assigned to fix the issue",
        ),
        sa.Column(
            "failure_description",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Detailed description of the problem reported by the submitter",
        ),
        sa.Column(
            "end_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=True,
            comment="Timestamp when the repair was completed and the issue was closed",
        ),
        sa.Column(
            "repair_description",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Technical details of the actions taken to resolve the failure",
        ),
        sa.Column(
            "comment",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Additional notes or remarks from the maintenance team",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the record was initially created",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the record was last modified",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
            name=op.f("failures_department_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"], ["machines.id"], name=op.f("failures_machine_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"], ["users.id"], name=op.f("failures_recipient_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["submitter_id"], ["users.id"], name=op.f("failures_submitter_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("failures_pkey")),
        comment="Core table tracking machine breakdowns and repair lifecycle",
    )
    op.create_index(op.f("ix_failures_id"), "failures", ["id"], unique=False)
    op.create_table(
        "attachments",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "failure_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Links the file to a specific failure report",
        ),
        sa.Column(
            "order_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Links the file to a scheduled maintenance order",
        ),
        sa.Column(
            "file_path",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Storage path or URI of the physical file",
        ),
        sa.Column(
            "uploaded_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp of the file upload",
        ),
        sa.ForeignKeyConstraint(
            ["failure_id"], ["failures.id"], name=op.f("attachments_failure_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order_calendar.id"], name=op.f("attachments_order_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("attachments_pkey")),
        comment="Stores metadata and file paths for user-uploaded documents",
    )
    op.create_index(op.f("ix_attachments_id"), "attachments", ["id"], unique=False)
    op.create_table(
        "part_history",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("part_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("machine_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("failure_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("quantity_change", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "transaction_type", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("reason", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["failure_id"], ["failures.id"], name=op.f("part_history_failure_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"], ["machines.id"], name=op.f("part_history_machine_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["part_id"], ["parts.id"], name=op.f("part_history_part_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("part_history_user_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("part_history_pkey")),
    )
    op.create_index(op.f("ix_part_history_id"), "part_history", ["id"], unique=False)
    op.create_table(
        "parts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "category_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Links to the category (e.g., Bearings, Electrical) for organizational grouping",
        ),
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Descriptive name or part number identifier",
        ),
        sa.Column(
            "type",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Classification of part type (e.g., consumables, strategic spare)",
        ),
        sa.Column(
            "quantity",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Current physical stock level in the warehouse",
        ),
        sa.Column(
            "min_quantity",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Threshold level for triggering automatic restocking notifications",
        ),
        sa.Column(
            "location",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Specific warehouse aisle/shelf identifier",
        ),
        sa.Column(
            "price",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
            comment="Unit cost of the part",
        ),
        sa.Column(
            "url_address",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="External URL for reordering or supplier reference",
        ),
        sa.Column(
            "docs",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Path or link to technical documentation/datasheets",
        ),
        sa.Column(
            "qr_code",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Unique identifier for mobile warehouse management",
        ),
        sa.Column(
            "producer",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Manufacturer or supplier of the part",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["part_categories.id"], name=op.f("parts_category_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("parts_pkey")),
        sa.UniqueConstraint(
            "qr_code",
            name=op.f("parts_qr_code_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Comprehensive inventory of spare parts and warehouse stock metadata",
    )
    op.create_index(op.f("ix_parts_id"), "parts", ["id"], unique=False)
    op.create_table(
        "machines",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Official designation or asset tag of the machine",
        ),
        sa.Column(
            "location",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Physical location on the production floor (e.g., Hall A, Sector 3)",
        ),
        sa.Column(
            "qr_code",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Unique QR identifier used for mobile scanning and quick asset retrieval",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Current operational state (e.g., 'operational', 'under_maintenance', 'out_of_service')",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the machine record was created",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the machine record was last updated",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("machines_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("machines_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "qr_code",
            name=op.f("machines_qr_code_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Core inventory of physical machines and production equipment",
    )
    op.create_index(op.f("ix_machines_id"), "machines", ["id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "parent_message_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Reference to a parent message to support threading/replies",
        ),
        sa.Column(
            "subject",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Topic or summary of the message",
        ),
        sa.Column(
            "content",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Main body text of the message",
        ),
        sa.Column(
            "sender_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="User who sent the message",
        ),
        sa.Column(
            "role_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Optional role-based broadcast target",
        ),
        sa.Column(
            "sent_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="Exact timestamp when the message was dispatched",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the record was initially created",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the record was last modified",
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["messages.id"],
            name=op.f("messages_parent_message_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["role_id"], ["roles.id"], name=op.f("messages_role_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"], ["users.id"], name=op.f("messages_sender_id_fkey")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("messages_pkey")),
        comment="Central storage for internal messages and threads",
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_table(
        "message_recipients",
        sa.Column(
            "message_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the specific message broadcasted",
        ),
        sa.Column(
            "recipient_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the targeted user receiving the message",
        ),
        sa.Column(
            "is_read",
            sa.BOOLEAN(),
            autoincrement=False,
            nullable=False,
            comment="Indicates whether the recipient has opened and read the message",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("message_recipients_message_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("message_recipients_recipient_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "message_id", "recipient_id", name=op.f("message_recipients_pkey")
        ),
        comment="Association table tracking message delivery and read status per user",
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Unique role identifier (e.g., 'Admin', 'Technician')",
        ),
        sa.Column(
            "description",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Detailed description of the role's purpose",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("roles_pkey")),
        sa.UniqueConstraint(
            "name",
            name=op.f("roles_name_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        comment="Dictionary of available user roles for access control",
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "part_compatibilities",
        sa.Column(
            "part_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the spare part",
        ),
        sa.Column(
            "machine_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the machine compatible with the part",
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
            name=op.f("part_compatibilities_machine_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["part_id"], ["parts.id"], name=op.f("part_compatibilities_part_id_fkey")
        ),
        sa.PrimaryKeyConstraint(
            "part_id", "machine_id", name=op.f("part_compatibilities_pkey")
        ),
        comment="Defines compatibility mapping between spare parts and machines",
    )
    op.create_table(
        "order_calendar",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "order_type_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="Reference to the classification of the maintenance task",
        ),
        sa.Column(
            "description",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Summary of the work to be performed",
        ),
        sa.Column(
            "principal_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
            comment="User who created or requested the order",
        ),
        sa.Column(
            "performed_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Technician assigned to execute the task",
        ),
        sa.Column(
            "machine_id",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
            comment="Target machine for the maintenance task",
        ),
        sa.Column(
            "comments",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
            comment="Additional notes regarding the execution or scope of work",
        ),
        sa.Column(
            "scheduled_date",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="Planned date and time for task execution",
        ),
        sa.Column(
            "status",
            sa.VARCHAR(),
            autoincrement=False,
            nullable=False,
            comment="Current execution state (e.g., 'scheduled', 'in_progress', 'completed')",
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the record was initially created",
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            comment="UTC timestamp when the record was last modified",
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"], ["machines.id"], name=op.f("order_calendar_machine_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["order_type_id"],
            ["order_types.id"],
            name=op.f("order_calendar_order_type_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["performed_id"],
            ["users.id"],
            name=op.f("order_calendar_performed_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["users.id"],
            name=op.f("order_calendar_principal_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("order_calendar_pkey")),
        comment="Central schedule for maintenance orders and tasks",
    )
    op.create_index(
        op.f("ix_order_calendar_id"), "order_calendar", ["id"], unique=False
    )
    # ### end Alembic commands ###
