"""remove_unique_constraint_from_part_name

Revision ID: 9c8941f9246a
Revises: 5875d9cb6f71
Create Date: 2026-07-16 09:17:44.476388

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "9c8941f9246a"
down_revision: Union[str, Sequence[str], None] = "5875d9cb6f71"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("parts_name_key"), "parts", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("parts_name_key"), "parts", ["name"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
