"""Add assigned_role_id to orders

Revision ID: f5b6f694b182
Revises: 725eb1cdc487
Create Date: 2026-08-08 09:35:50.092709

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5b6f694b182"
down_revision: Union[str, Sequence[str], None] = "725eb1cdc487"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "failures",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="UTC timestamp when the record was initially created",
        existing_nullable=False,
    )
    op.alter_column(
        "failures",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="UTC timestamp when the record was last modified",
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="UTC timestamp when the record was initially created",
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="UTC timestamp when the record was last modified",
        existing_nullable=False,
    )
    op.add_column(
        "order_calendar", sa.Column("assigned_role_id", sa.Integer(), nullable=True)
    )
    op.alter_column(
        "order_calendar",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="UTC timestamp when the record was initially created",
        existing_nullable=False,
    )
    op.alter_column(
        "order_calendar",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="UTC timestamp when the record was last modified",
        existing_nullable=False,
    )
    op.create_foreign_key(None, "order_calendar", "roles", ["assigned_role_id"], ["id"])
    op.alter_column(
        "users",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="UTC timestamp when the record was initially created",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_comment="UTC timestamp when the record was last modified",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="UTC timestamp when the record was last modified",
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="UTC timestamp when the record was initially created",
        existing_nullable=False,
    )
    op.drop_constraint(None, "order_calendar", type_="foreignkey")
    op.alter_column(
        "order_calendar",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="UTC timestamp when the record was last modified",
        existing_nullable=False,
    )
    op.alter_column(
        "order_calendar",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="UTC timestamp when the record was initially created",
        existing_nullable=False,
    )
    op.drop_column("order_calendar", "assigned_role_id")
    op.alter_column(
        "messages",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="UTC timestamp when the record was last modified",
        existing_nullable=False,
    )
    op.alter_column(
        "messages",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="UTC timestamp when the record was initially created",
        existing_nullable=False,
    )
    op.alter_column(
        "failures",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="UTC timestamp when the record was last modified",
        existing_nullable=False,
    )
    op.alter_column(
        "failures",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_comment="UTC timestamp when the record was initially created",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
