"""Initial CMMS tables

Revision ID: fc5443389ed0
Revises: 
Create Date: 2026-07-09 17:12:12.870101

"""

from typing import Sequence, Union

from alembic import op  # type: ignore
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fc5443389ed0"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(), nullable=False, comment="Name of the department"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Table for departments wchich are responsible for machines and failures",
    )
    op.create_index(op.f("ix_departments_id"), "departments", ["id"], unique=False)
    op.create_table(
        "machines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Name of the machine"),
        sa.Column(
            "location", sa.String(), nullable=False, comment="Location of the machine"
        ),
        sa.Column(
            "qr_code", sa.String(), nullable=False, comment="QR code of the machine"
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Status of the machine (e.g., operational, under maintenance, out of service)",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when the machine was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when the machine was last updated",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("qr_code"),
        comment="Table for machines",
    )
    op.create_index(op.f("ix_machines_id"), "machines", ["id"], unique=False)
    op.create_table(
        "order_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(), nullable=False, comment="Name of the order type"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Table for order types",
    )
    op.create_index(op.f("ix_order_types_id"), "order_types", ["id"], unique=False)
    op.create_table(
        "part_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(), nullable=False, comment="Name of the part category"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Table for part categories",
    )
    op.create_index(
        op.f("ix_part_categories_id"), "part_categories", ["id"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Name of the role"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        comment="Table for user roles",
    )
    op.create_index(op.f("ix_roles_id"), "roles", ["id"], unique=False)
    op.create_table(
        "parts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "category_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to the part_categories table",
        ),
        sa.Column("name", sa.String(), nullable=False, comment="Name of the part"),
        sa.Column("type", sa.String(), nullable=False, comment="Type of the part"),
        sa.Column(
            "quantity",
            sa.Integer(),
            nullable=False,
            comment="Quantity of the part in stock",
        ),
        sa.Column(
            "min_quantity",
            sa.Integer(),
            nullable=False,
            comment="Minimum quantity of the part in stock",
        ),
        sa.Column(
            "location",
            sa.String(),
            nullable=False,
            comment="Location of the part in the warehouse",
        ),
        sa.Column("price", sa.Double(), nullable=False, comment="Price of the part"),
        sa.Column(
            "url_address",
            sa.String(),
            nullable=True,
            comment="URL address of the part (nullable)",
        ),
        sa.Column(
            "docs",
            sa.String(),
            nullable=True,
            comment="Documentation of the part (nullable)",
        ),
        sa.Column(
            "qr_code", sa.String(), nullable=False, comment="QR code of the part"
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["part_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("qr_code"),
        comment="Table for parts",
    )
    op.create_index(op.f("ix_parts_id"), "parts", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False, comment="Name of the user"),
        sa.Column(
            "lastname", sa.String(), nullable=False, comment="Last name of the user"
        ),
        sa.Column(
            "sap_number", sa.String(), nullable=False, comment="SAP number of the user"
        ),
        sa.Column(
            "role_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to the roles table",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sap_number"),
        comment="Table for users",
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "failures",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "submitter_id",
            sa.Integer(),
            nullable=False,
            comment="User who submitted the failure",
        ),
        sa.Column(
            "machine_id",
            sa.Integer(),
            nullable=False,
            comment="Machine associated with the failure",
        ),
        sa.Column(
            "department_id",
            sa.Integer(),
            nullable=False,
            comment="Department associated with the failure",
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Status of the failure (e.g., 'open', 'in_progress', 'closed')",
        ),
        sa.Column(
            "recipient_id",
            sa.Integer(),
            nullable=True,
            comment="User assigned to handle the failure",
        ),
        sa.Column(
            "failure_description",
            sa.String(),
            nullable=False,
            comment="Description of the failure",
        ),
        sa.Column(
            "end_date",
            sa.DateTime(),
            nullable=True,
            comment="Date when the failure was resolved",
        ),
        sa.Column(
            "repair_description",
            sa.String(),
            nullable=True,
            comment="Description of the repair performed",
        ),
        sa.Column(
            "comment",
            sa.String(),
            nullable=True,
            comment="Additional comments regarding the failure",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["department_id"],
            ["departments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["submitter_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Table for failures",
    )
    op.create_index(op.f("ix_failures_id"), "failures", ["id"], unique=False)
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("parent_message_id", sa.Integer(), nullable=True),
        sa.Column(
            "subject", sa.String(), nullable=False, comment="Subject of the message"
        ),
        sa.Column(
            "content", sa.String(), nullable=False, comment="Content of the message"
        ),
        sa.Column("sender_id", sa.Integer(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["parent_message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["roles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Table for messages",
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_table(
        "order_calendar",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "order_type_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to the order_types table",
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=False,
            comment="Description of the task or event",
        ),
        sa.Column(
            "principal_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to the users table for the principal user",
        ),
        sa.Column(
            "performed_id",
            sa.Integer(),
            nullable=True,
            comment="Foreign key to the users table for the user who performed the task",
        ),
        sa.Column(
            "machine_id",
            sa.Integer(),
            nullable=True,
            comment="Foreign key to the machines table",
        ),
        sa.Column(
            "comments",
            sa.String(),
            nullable=True,
            comment="Additional comments or notes",
        ),
        sa.Column(
            "scheduled_date",
            sa.DateTime(),
            nullable=False,
            comment="Scheduled date and time for the task or event",
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Status of the task or event (e.g., 'scheduled', 'completed', 'canceled')",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when the record was created",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when the record was last updated",
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_type_id"],
            ["order_types.id"],
        ),
        sa.ForeignKeyConstraint(
            ["performed_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["principal_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Table for order calendar entries",
    )
    op.create_index(
        op.f("ix_order_calendar_id"), "order_calendar", ["id"], unique=False
    )
    op.create_table(
        "part_compatibilities",
        sa.Column(
            "part_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to parts table",
        ),
        sa.Column(
            "machine_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to machines table",
        ),
        sa.ForeignKeyConstraint(
            ["machine_id"],
            ["machines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
        ),
        sa.PrimaryKeyConstraint("part_id", "machine_id"),
        comment="Table for part compatibilities",
    )
    op.create_table(
        "attachments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "failure_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to the failures table",
        ),
        sa.Column(
            "order_id",
            sa.Integer(),
            nullable=True,
            comment="Foreign key to the orders table (nullable)",
        ),
        sa.Column(
            "file_path",
            sa.String(),
            nullable=False,
            comment="Path to the attachment file",
        ),
        sa.Column(
            "uploaded_at",
            sa.DateTime(),
            nullable=False,
            comment="Timestamp when the attachment was uploaded",
        ),
        sa.ForeignKeyConstraint(
            ["failure_id"],
            ["failures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order_calendar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Table for attachments",
    )
    op.create_index(op.f("ix_attachments_id"), "attachments", ["id"], unique=False)
    op.create_table(
        "failure_parts",
        sa.Column(
            "failure_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to failures table",
        ),
        sa.Column(
            "part_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to parts table",
        ),
        sa.Column(
            "quantity_used",
            sa.Integer(),
            nullable=False,
            comment="Quantity of the part used in the failure",
        ),
        sa.ForeignKeyConstraint(
            ["failure_id"],
            ["failures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["parts.id"],
        ),
        sa.PrimaryKeyConstraint("failure_id", "part_id"),
        comment="Table for failure parts",
    )
    op.create_table(
        "message_recipients",
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("recipient_id", sa.Integer(), nullable=False),
        sa.Column(
            "is_read",
            sa.Boolean(),
            nullable=False,
            comment="Has the user read this message?",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("message_id", "recipient_id"),
        comment="Table linking messages to their recipients",
    )
    op.create_table(
        "order_checklist_items",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "order_calendar_id",
            sa.Integer(),
            nullable=False,
            comment="Foreign key to order_calendar table",
        ),
        sa.Column(
            "task_description",
            sa.String(),
            nullable=False,
            comment="Description of the checklist item",
        ),
        sa.Column(
            "status",
            sa.String(),
            nullable=False,
            comment="Status of the checklist item",
        ),
        sa.Column(
            "comments",
            sa.String(),
            nullable=True,
            comment="Additional comments for the checklist item",
        ),
        sa.ForeignKeyConstraint(
            ["order_calendar_id"],
            ["order_calendar.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="Table for order checklist items",
    )
    op.create_index(
        op.f("ix_order_checklist_items_id"),
        "order_checklist_items",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_order_checklist_items_id"), table_name="order_checklist_items"
    )
    op.drop_table("order_checklist_items")
    op.drop_table("message_recipients")
    op.drop_table("failure_parts")
    op.drop_index(op.f("ix_attachments_id"), table_name="attachments")
    op.drop_table("attachments")
    op.drop_table("part_compatibilities")
    op.drop_index(op.f("ix_order_calendar_id"), table_name="order_calendar")
    op.drop_table("order_calendar")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_failures_id"), table_name="failures")
    op.drop_table("failures")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_parts_id"), table_name="parts")
    op.drop_table("parts")
    op.drop_index(op.f("ix_roles_id"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("ix_part_categories_id"), table_name="part_categories")
    op.drop_table("part_categories")
    op.drop_index(op.f("ix_order_types_id"), table_name="order_types")
    op.drop_table("order_types")
    op.drop_index(op.f("ix_machines_id"), table_name="machines")
    op.drop_table("machines")
    op.drop_index(op.f("ix_departments_id"), table_name="departments")
    op.drop_table("departments")
    # ### end Alembic commands ###
